# docker-compose.yml
version: '3'

networks:
  db_network:
    driver: bridge 

volumes:
  postgres_volume:

services:

  browser:
    container_name: browser
    image: selenium/standalone-firefox:4.0.0-alpha-7-prerelease-20200921
    ports:
      - "4444:4444"
    volumes:
     - /dev/shm:/dev/shm

  parser:
    container_name: parser
    build: ./exch_parser_kusrkz
    ports:
      - "5081:5081"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=5081'
    command: flask run --host=0.0.0.0 --port=5081
    depends_on:
     - manager
     - browser

  manager:
    container_name: manager
    build: ./exch_manager
    ports:
      - "5080:5080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=torn
      - POSTGRES_PASSWORD=helicopter
      - POSTGRES_DB=exchdb
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=5080'
    command: flask run --host=0.0.0.0 --port=5080
    depends_on:
      - db
    networks:
      - db_network

  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    env_file:
     - ./db/database.conf
    ports:
     - 5433:5432
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db/scripts/:/docker-entrypoint-initdb.d/
    networks:
      - db_network
